# using Ubuntu 18.04
dist: xenial

services:
  # to link travis and docker
  - docker

# for testing
language: java

# using java 17 for file
jdk:
  - openjdk17

before_install:
  - chmod +x mvnw
  - mvn clean
  - mvn package
  - echo "$DOCKER_PASS" | docker login  -u "$DOCKER_USER" --password-stdin
  - docker pull openjdk:17-jdk-alpine

# running maven install on code
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V