version: '3.8'

services:

  testingproj-container:
    image: microservices:0.0.1-SNAPSHOT
    container_name: microservices
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/microservices-container
    ports:
      - 8081:8081
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data

volumes:
  data: {}

networks:
  default:
    name: mongodb_network