version: '3.8'

services:
  #our program container
  testingproj-container:
    image: microservices:0.0.1-SNAPSHOT     #the image name
    container_name: microservices           #container name
    build:
      context: ./
      dockerfile: Dockerfile              #access dockerfile
    volumes:
      - /data/microservices-container     #store persisting data
    ports:
      - 8081:8081                         #program port
    links:
      - mongo                             #links with mongo container

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data

volumes:
  data: {}

networks:
  default:      #using default network
    name: mongodb_network